# local configuration
server:
  port: 8081

# remote server configuration
remote:
  restapi:
    ms2:
      product:
        rest:
          url: http://localhost:8082/ms2/product/rest
        grpc:
          url: http://localhost:8082/ms2/product/grpc

